name: CCAP
favicon: null
layout_spectrum: 0.7271452723070979
typography_spectrum: 0.12477455078624189
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.1453959192149341
  lightness: 0.6684575327672064
  saturation: 0.7558662767987698
  rhythmicContrast: 0.004740894306451082
purpose: []
